baseURL = 'https://miguoliang.github.io/tomato-clock-cli/'
languageCode = 'en-us'
title = 'Tomato Clock CLI'
theme = 'hugo-book'

[params]
  bookFavicon = 'favicon.ico'
  bookLogo = 'logo.png'

[markup.goldmark.renderer]
  unsafe = true